[package]
name = "proto-dryb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proto-dryb-derive = { path = "../proto-dryb-derive" }

[dev-dependencies]
criterion = "0.5.1"
